contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #fastqdemultiplextest channel"
    url: https://nfcore.slack.com/channels/fastqdemultiplextest
    about: Discussion about the nf-core/fastqdemultiplextest pipeline
